# 第7章 数据清洗和准备

In [2]:
import numpy as np
import pandas as pd

## 7.1 处理缺失数据

In [6]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [7]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [8]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 滤除缺失数据

In [9]:
from numpy import nan as NA
data = pd.Series([1,NA,3.5,NA,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [13]:
data.dropna(how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [15]:
data.dropna(axis = 1, how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA
df

0         1         2
0  0.567162       NaN       NaN
1 -1.462288       NaN       NaN
2  3.363394       NaN -0.662647
3 -0.476198       NaN  0.371522
4  1.299724 -1.304705 -0.358132
5 -0.983649 -0.214289  0.117365
6  2.833401  0.855303 -0.085704

In [17]:
df.dropna()

0         1         2
4  1.299724 -1.304705 -0.358132
5 -0.983649 -0.214289  0.117365
6  2.833401  0.855303 -0.085704

In [18]:
df.dropna(thresh = 2)

0         1         2
2  3.363394       NaN -0.662647
3 -0.476198       NaN  0.371522
4  1.299724 -1.304705 -0.358132
5 -0.983649 -0.214289  0.117365
6  2.833401  0.855303 -0.085704

### 填充缺失数据

In [19]:
df.fillna(0)

0         1         2
0  0.567162  0.000000  0.000000
1 -1.462288  0.000000  0.000000
2  3.363394  0.000000 -0.662647
3 -0.476198  0.000000  0.371522
4  1.299724 -1.304705 -0.358132
5 -0.983649 -0.214289  0.117365
6  2.833401  0.855303 -0.085704

In [20]:
df.fillna({1:0.5,2:0})

0         1         2
0  0.567162  0.500000  0.000000
1 -1.462288  0.500000  0.000000
2  3.363394  0.500000 -0.662647
3 -0.476198  0.500000  0.371522
4  1.299724 -1.304705 -0.358132
5 -0.983649 -0.214289  0.117365
6  2.833401  0.855303 -0.085704

In [21]:
_ = df.fillna(0,inplace = True)
df

0         1         2
0  0.567162  0.000000  0.000000
1 -1.462288  0.000000  0.000000
2  3.363394  0.000000 -0.662647
3 -0.476198  0.000000  0.371522
4  1.299724 -1.304705 -0.358132
5 -0.983649 -0.214289  0.117365
6  2.833401  0.855303 -0.085704

In [22]:
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:,1] = NA
df.iloc[4:,2] = NA
df

0         1         2
0 -0.612724 -0.764659 -0.042540
1 -0.417910 -0.896104  1.068295
2 -1.176078       NaN  0.926184
3 -1.720918       NaN  0.604014
4  0.270502       NaN       NaN
5  1.159269       NaN       NaN

In [23]:
df.fillna(method = 'ffill')

0         1         2
0 -0.612724 -0.764659 -0.042540
1 -0.417910 -0.896104  1.068295
2 -1.176078 -0.896104  0.926184
3 -1.720918 -0.896104  0.604014
4  0.270502 -0.896104  0.604014
5  1.159269 -0.896104  0.604014

In [24]:
df.fillna(method = 'ffill',limit = 2)

0         1         2
0 -0.612724 -0.764659 -0.042540
1 -0.417910 -0.896104  1.068295
2 -1.176078 -0.896104  0.926184
3 -1.720918 -0.896104  0.604014
4  0.270502       NaN  0.604014
5  1.159269       NaN  0.604014

In [25]:
data = pd.Series([1,NA,3.5,NA,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 7.2 数据转换

### 移除重复数据

In [26]:
data = pd.DataFrame({'k1':['one','two'] * 3 + ['two'],
                    'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [27]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [28]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [29]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [30]:
data.drop_duplicates(['k1','k2'],keep = 'last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### 利用函数或映射进行数据转换

In [31]:
data = pd.DataFrame({'food': ['bacon','pulled pork','bacon',
                             'Pastrami','corned beef','Bacon',
                              'pastrami','honey ham', 'nova lox'],
                    'ounces': [4,3,12,6,7.5,8,3,5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [32]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [37]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [38]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [39]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### 替换值

In [40]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [41]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [43]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [44]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [46]:
data.replace({-999:np.nan,-1000:0}) #ata.replace方法与data.str.replace不同，后者做的是字符串的元素级替换。

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 重命名轴索引

In [47]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                     index=['Ohio', 'Colorado', 'New York'],
                     columns=['one', 'two', 'three', 'four'])

In [48]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [49]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [51]:
data.rename(index = {'OHIO':'INDIANA'},columns = {'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [52]:
data.rename(index = {'OHIO':'INDIANA'},inplace = True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### 离散化和面元划分

In [53]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [54]:
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [55]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [56]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [57]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [58]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [59]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [60]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.72, 0.96], (0.49, 0.72], (0.72, 0.96], (0.25, 0.49], (0.72, 0.96], ..., (0.25, 0.49], (0.49, 0.72], (0.013, 0.25], (0.72, 0.96], (0.72, 0.96]]
Length: 20
Categories (4, interval[float64]): [(0.013, 0.25] < (0.25, 0.49] < (0.49, 0.72] < (0.72, 0.96]]

In [61]:
data = np.random.randn(1000)  # Normally distributed
cats = pd.qcut(data, 4)  # Cut into quartiles
cats

[(-3.745, -0.71], (-3.745, -0.71], (0.576, 3.184], (-3.745, -0.71], (-0.71, -0.0277], ..., (0.576, 3.184], (-3.745, -0.71], (-3.745, -0.71], (-0.71, -0.0277], (-0.0277, 0.576]]
Length: 1000
Categories (4, interval[float64]): [(-3.745, -0.71] < (-0.71, -0.0277] < (-0.0277, 0.576] < (0.576, 3.184]]

In [63]:
pd.value_counts(cats)

(0.576, 3.184]      250
(-0.0277, 0.576]    250
(-0.71, -0.0277]    250
(-3.745, -0.71]     250
dtype: int64

In [64]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-3.745, -1.355], (-1.355, -0.0277], (1.388, 3.184], (-1.355, -0.0277], (-1.355, -0.0277], ..., (-0.0277, 1.388], (-1.355, -0.0277], (-3.745, -1.355], (-1.355, -0.0277], (-0.0277, 1.388]]
Length: 1000
Categories (4, interval[float64]): [(-3.745, -1.355] < (-1.355, -0.0277] < (-0.0277, 1.388] < (1.388, 3.184]]

### 检测和过滤异常值

In [65]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.073086    -0.001110     0.016528    -0.022880
std       1.008730     1.024728     0.994814     1.014589
min      -4.164736    -3.578235    -3.198306    -3.201247
25%      -0.748980    -0.677370    -0.646004    -0.688223
50%      -0.122039    -0.030918     0.019657    -0.055408
75%       0.572672     0.728917     0.645609     0.674677
max       3.524880     3.500591     3.012057     3.140694

In [66]:
col = data[2]
col[np.abs(col) > 3]

213    3.012057
601   -3.198306
866   -3.088855
Name: 2, dtype: float64

In [67]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
4    3.524880  0.052036  0.633850 -0.973450
43  -0.703690 -3.578235 -0.021481 -0.513100
76   3.171713 -0.226107  1.002365  0.411129
206 -3.808219 -0.776002 -1.242564  1.232790
213  0.295860 -0.366795  3.012057 -1.373437
441  3.358077 -1.242083  0.112669  0.347445
451  0.004909 -0.375686 -0.315819 -3.201247
601  0.177792 -0.101409 -3.198306  1.197581
677 -0.616953  0.813729  0.585776  3.140694
861 -0.339452  3.500591  0.340069 -0.270222
866 -0.823355  0.549574 -3.088855 -1.322905
880  0.993759 -1.277058  0.030395  3.134633
881 -1.506799 -3.143543  1.712369 -0.407803
905 -4.164736 -0.997823 -0.186271  0.651560
976 -3.098250 -1.631143 -0.856266  0.184176

In [68]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.072069    -0.000889     0.016803    -0.022954
std       0.998226     1.020843     0.993882     1.013137
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.748980    -0.677370    -0.646004    -0.688223
50%      -0.122039    -0.030918     0.019657    -0.055408
75%       0.572672     0.728917     0.645609     0.674677
max       3.000000     3.000000     3.000000     3.000000

In [69]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0 -1.0  1.0
1  1.0  1.0  1.0  1.0
2 -1.0  1.0  1.0  1.0
3  1.0 -1.0 -1.0  1.0
4  1.0  1.0  1.0 -1.0

### 排列和随机采样

In [70]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
sampler

array([0, 2, 3, 1, 4])

In [72]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [73]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7
4  16  17  18  19

In [74]:
df.sample(n=3)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
1   4   5   6   7

In [75]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

1    7
0    5
4    4
0    5
4    4
3    6
2   -1
3    6
3    6
4    4
dtype: int64

### 计算指标/哑变量

In [76]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                 'data1': range(6)})
pd.get_dummies(df['key'])
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [86]:
import warnings
warnings.filterwarnings('ignore')
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('movies.dat')
movies[:10]

movie_id                               title                        genres
0         1                    Toy_Story_(1995)   Animation|Children's|Comedy
1         2                      Jumanji_(1995)  Adventure|Children's|Fantasy
2         3             Grumpier_Old_Men_(1995)                Comedy|Romance
3         4            Waiting_to_Exhale_(1995)                  Comedy|Drama
4         5  Father_of_the_Bride_Part_II_(1995)                        Comedy
5         6                         Heat_(1995)         Action|Crime|Thriller
6         7                      Sabrina_(1995)                Comedy|Romance
7         8                 Tom_and_Huck_(1995)          Adventure|Children's
8         9                 Sudden_Death_(1995)                        Action
9        10                    GoldenEye_(1995)     Action|Adventure|Thriller

In [87]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller'], dtype=object)

In [88]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [89]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [90]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                                      1
title                          Toy_Story_(1995)
genres              Animation|Children's|Comedy
Genre_Animation                               0
Genre_Children's                              0
Genre_Comedy                                  0
Genre_Adventure                               0
Genre_Fantasy                                 0
Genre_Romance                                 0
Genre_Drama                                   0
Genre_Action                                  0
Genre_Crime                                   0
Genre_Thriller                                0
Name: 0, dtype: object

In [91]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [92]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 7.3 字符串操作

### 字符串对象方法

In [93]:
val = 'a,b,  guido'
val.split(',')

['a', 'b', '  guido']

In [94]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [95]:
first, second, third = pieces
first + '::' + second + '::' + third

'a::b::guido'

In [96]:
'::'.join(pieces)

'a::b::guido'

In [97]:
'guido' in val

True

In [98]:
val.index(',')

1

In [99]:
val.find(':')

-1

In [100]:
val.index(':')

ValueError: substring not found

In [101]:
val.count(',')

2

In [102]:
val.replace(',', '::')

'a::b::  guido'

In [103]:
val.replace(',', '')

'ab  guido'

### 正则表达式

In [104]:
import re

In [105]:
text = "foo    bar\t baz  \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [107]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [108]:
regex.findall(text)

['    ', '\t ', '  \t']

In [196]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

# re.IGNORECASE makes the regex case-insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [197]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [198]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [199]:
text[m.start():m.end()]

'dave@google.com'

In [200]:
print(regex.match(text))

None


In [201]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [204]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [205]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [206]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



### pandas的矢量化字符串函数

In [209]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [210]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [211]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [212]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [213]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [214]:
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [215]:
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [216]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [217]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object