# 第05章 pandas入门 

In [1]:
import pandas as pd

In [2]:
from pandas import Series,DataFrame

## 5.1 pandas的数据结构介绍 

### Series

In [3]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4,7,-5,3],index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2['a']

-5

In [8]:
obj2['d'] = 6
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [9]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [10]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [11]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [12]:
'b' in obj2

True

In [13]:
'e' in obj2

False

In [14]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [15]:
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [16]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [18]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [19]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [22]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [23]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [24]:
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [25]:
data = {'state':['Ohio','Ohio','Ohio','Nevada', 'Nevada', 'Nevada'],'year': [2000, 2001, 2002, 2001, 2002, 2003],'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [26]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [27]:
pd.DataFrame(data,columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [28]:
frame2 = pd.DataFrame(data,columns = ['year','state','pop','debt'],index = ['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [29]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [30]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [31]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [32]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [33]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [34]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [35]:
val = pd.Series([-1.2,-1.5,-1.7],index = ['two','four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [36]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [37]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [38]:
pop = {'Nevada': {2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [39]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [40]:
pd.DataFrame(pop,index = [2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [41]:
pdata = {'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [42]:
frame3.index.name = 'year';frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [43]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [44]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 索引对象

In [45]:
obj = pd.Series(range(3),index = ['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [46]:
index[1:]

Index(['b', 'c'], dtype='object')

In [47]:
index[1] = 'd' #Index对象是不可变的，因此用户不能对其进行修改

TypeError: Index does not support mutable operations

In [48]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [49]:
obj2 = pd.Series([1.5,-2.5,0],index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [50]:
obj2.index is labels

True

In [51]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [52]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [53]:
'Ohio' in frame3.columns

True

In [54]:
2003 in frame3.index

False

In [55]:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 基本功能 

### 重新索引

In [56]:
obj = pd.Series([4.5,7.2,-5.3])
obj

0    4.5
1    7.2
2   -5.3
dtype: float64

In [57]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [58]:
obj3 = pd.Series(['blue','purple','yellow'],index = [0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [59]:
obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [60]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index = ['a','c','d'],columns = ['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [61]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [62]:
states = ['Texas','Utah','California']
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### 丢弃指定轴上的项

In [78]:
obj = pd.Series(np.arange(5.),index = ['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [79]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [80]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [81]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index = ['Ohio','Colorado','Utah','New York'],columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [82]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [83]:
data.drop('two',axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [84]:
data.drop(['two','four'],axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [85]:
obj.drop('c',inplace = True)
obj   #小心使用inplace，它会销毁所有被删除的数据。

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 索引、选取和过滤

In [86]:
obj = pd.Series(np.arange(4.),index = ['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [87]:
obj['b']

1.0

In [88]:
obj[1]

1.0

In [89]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [90]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [91]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [92]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [93]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [96]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [97]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index = ['Ohio','Colorado','Utah','New York'],columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [99]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [100]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [101]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [102]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [103]:
data[data < 5] =0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 用loc和iloc进行选取

In [104]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [105]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [106]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [107]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [108]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [109]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### 整数索引

In [117]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [118]:
#ser[-1] 报错，产生歧义

In [113]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [119]:
ser2 = pd.Series(np.arange(3.),index = ['a','b','c'])
ser2[-1] #对于非整数索引，不会产生歧义

2.0

In [120]:
ser[:1]

0    0.0
dtype: float64

In [121]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [122]:
ser.iloc[:1]

0    0.0
dtype: float64

### 算术运算和数据对齐

In [123]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index = ['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index = ['a','c','e','f','g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [124]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [125]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [127]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns = list('bcd'),index = ['Ohio','Texas','Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape(4,3),columns = list('bde'),index = ['Utah','Ohio','Texas','Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [128]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [129]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [130]:
df1 = pd.DataFrame({'A': [1,2]})
df2 = pd.DataFrame({'B': [3,4]})
df1

A
0  1
1  2

In [131]:
df2

B
0  3
1  4

In [132]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

### 在算术方法中填充值

In [133]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),columns = list('abcde'))
df2.loc[1,'b'] = np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [134]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [135]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [136]:
df1.add(df2,fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [137]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [138]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [139]:
df1.reindex(columns = df2.columns,fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### DataFrame和Series之间的运算

In [140]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [141]:
arr[0]

array([0., 1., 2., 3.])

In [142]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [143]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),columns = list('bde'),index = ['Utah','Ohio','Texas','Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [144]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [145]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [146]:
series2 = pd.Series(range(3),index = ['b','e','f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [147]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [148]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [149]:
frame.sub(series3,axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 函数应用和映射

In [150]:
frame = pd.DataFrame(np.random.randn(4,3),columns = list('bde'),index = ['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah   -0.900748  1.880925  1.624293
Ohio   -0.443073 -0.761129 -1.587319
Texas  -0.473111 -0.305635  0.712037
Oregon -0.843295  1.535059 -1.359071

In [151]:
np.abs(frame)

b         d         e
Utah    0.900748  1.880925  1.624293
Ohio    0.443073  0.761129  1.587319
Texas   0.473111  0.305635  0.712037
Oregon  0.843295  1.535059  1.359071

In [152]:
f = lambda x : x.max() - x.min()
frame.apply(f)

b    0.457675
d    2.642055
e    3.211612
dtype: float64

In [153]:
frame.apply(f,axis = 'columns')

Utah      2.781674
Ohio      1.144246
Texas     1.185148
Oregon    2.894130
dtype: float64

In [154]:
def f(x):
    return pd.Series([x.min(),x.max()],index = ['min','max'])
frame.apply(f)

b         d         e
min -0.900748 -0.761129 -1.587319
max -0.443073  1.880925  1.624293

In [155]:
format = lambda x:'%.2f' %x
frame.applymap(format)

b      d      e
Utah    -0.90   1.88   1.62
Ohio    -0.44  -0.76  -1.59
Texas   -0.47  -0.31   0.71
Oregon  -0.84   1.54  -1.36

In [156]:
frame['e'].map(format)

Utah       1.62
Ohio      -1.59
Texas      0.71
Oregon    -1.36
Name: e, dtype: object

### 排序和排名

In [157]:
obj = pd.Series(range(4),index = ['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [158]:
frame.sort_index(axis = 1)

b         d         e
Utah   -0.900748  1.880925  1.624293
Ohio   -0.443073 -0.761129 -1.587319
Texas  -0.473111 -0.305635  0.712037
Oregon -0.843295  1.535059 -1.359071

In [159]:
frame.sort_index(axis = 1,ascending = False)

e         d         b
Utah    1.624293  1.880925 -0.900748
Ohio   -1.587319 -0.761129 -0.443073
Texas   0.712037 -0.305635 -0.473111
Oregon -1.359071  1.535059 -0.843295

In [160]:
obj = pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [161]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [162]:
frame = pd.DataFrame({'b': [4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [163]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [164]:
frame.sort_values(by = ['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [165]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [166]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [167]:
# Assign tie values the maximum rank in the group
obj.rank(ascending = False,method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [168]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [169]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### 带有重复标签的轴索引

In [170]:
obj = pd.Series(range(5),index = ['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [171]:
obj.index.is_unique

False

In [172]:
obj['a']

a    0
a    1
dtype: int64

In [173]:
obj['c']

4

In [174]:
df = pd.DataFrame(np.random.randn(4,3),index = ['a','a','b','b'])
df 

0         1         2
a -0.090317  0.041058 -0.174960
a -0.988549 -0.712236 -0.881548
b  0.191956  1.095362 -0.143498
b -0.965276  0.081311 -0.468526

In [175]:
df.loc['b']

0         1         2
b  0.191956  1.095362 -0.143498
b -0.965276  0.081311 -0.468526

## 5.3 汇总和计算描述统计

In [176]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index = ['a','b','c','d'],columns = ['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [178]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [179]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [181]:
df.mean(axis = 'columns',skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [182]:
df.idxmax()

one    b
two    d
dtype: object

In [183]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [184]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [185]:
obj = pd.Series(['a','a','b','c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### 相关系数与协方差

In [190]:
import pandas_datareader.data as web

In [192]:
all_data = {ticker:web.get_data_yahoo(ticker)
            for ticker in ['AAPL','IBM','MSFT','GOOG']}
price = pd.DataFrame({ticker:data['Adj Close']
                      for ticker,data in all_data.items()})
volume = pd.DataFrame({ticker:data['Volume']
                       for ticker,data in all_data.items()})

In [194]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-06-18  0.023518  0.010597  0.017388  0.010160
2019-06-19 -0.002923  0.005133  0.003921 -0.001151
2019-06-20  0.008036  0.012912  0.009286  0.008246
2019-06-21 -0.003409  0.002521  0.000146  0.009411
2019-06-24 -0.001006  0.001078  0.005914 -0.005669

In [195]:
returns['MSFT'].corr(returns['IBM'])

0.48704756199916444

In [196]:
returns['MSFT'].cov(returns['IBM'])

8.674425220966523e-05

In [197]:
returns.MSFT.corr(returns.IBM)

0.48704756199916444

In [201]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.375336  0.452785  0.457600
IBM   0.375336  1.000000  0.487048  0.402964
MSFT  0.452785  0.487048  1.000000  0.537304
GOOG  0.457600  0.402964  0.537304  1.000000

In [200]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000270  0.000076  0.000108  0.000116
IBM   0.000076  0.000152  0.000087  0.000077
MSFT  0.000108  0.000087  0.000209  0.000120
GOOG  0.000116  0.000077  0.000120  0.000239

In [202]:
returns.corrwith(returns.IBM)

AAPL    0.375336
IBM     1.000000
MSFT    0.487048
GOOG    0.402964
dtype: float64

In [203]:
returns.corrwith(volume)

AAPL   -0.059878
IBM    -0.156340
MSFT   -0.090440
GOOG   -0.020999
dtype: float64

### 唯一值、值计数以及成员资格

In [204]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [205]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [206]:
pd.value_counts(obj.values,sort = False)

c    3
b    2
d    1
a    3
dtype: int64

In [207]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [208]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [209]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [211]:
to_match = pd.Series(['c','a','b','b','c','a'])
unique_vals = pd.Series(['c','b','a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [212]:
data = pd.DataFrame({'Qu1': [1,3,4,3,4],'Qu2': [2,3,1,2,3],'Qu3': [1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [213]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0