1.导入numpy

In [1]:
import numpy as np

2.打印numpy版本和配置说明

In [6]:
print('numpy版本：{}'.format(np.__version__))
print('numpy配置说明：{}'.format(np.show_config()))

numpy版本：1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\m

3.创建一个长度为10的空向量

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4.如何找到一个数组的内存大小

In [20]:
z = np.zeros((10,10))
print('{:d} bytes'.format(z.size*z.itemsize))

800 bytes


5.如何找到numpy中add的说明文档

In [21]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

6.创建一个长度为10并且除了第五个值为1的空向量

In [23]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.创建一个值域为10到49的向量

In [26]:
z = np.array(range(10,50))
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8.反转一个向量

In [28]:
print(z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9.创建一个3*3且值为0到8的向量

In [30]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10.找到数组中非0元素的位置索引

In [39]:
z = np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4], dtype=int64),)


11.创建一个3*3的单位矩阵

In [44]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12.创建一个3 * 3 * 3的随机矩阵

In [47]:
z = np.random.random((3,3,3))
print(z)

[[[0.33886418 0.97947952 0.71068066]
  [0.7652113  0.35381245 0.18132056]
  [0.92139523 0.62669267 0.37752872]]

 [[0.14059758 0.66983567 0.51136685]
  [0.19653436 0.16192285 0.16183191]
  [0.73672902 0.81814005 0.39420663]]

 [[0.79707233 0.26420858 0.09338546]
  [0.44801185 0.41227899 0.54168599]
  [0.42950445 0.80594644 0.24232151]]]


13.创建一个10*10的随机矩阵，同时找到最大值和最小值

In [50]:
z = np.random.random((10,10))
print('随机矩阵：{}\n 最大值： {} \n 最小值： {}'.format(z,z.max(),z.min()))

随机矩阵：[[0.77780915 0.71838865 0.18471453 0.83140847 0.16955748 0.98308883
  0.65828163 0.87781282 0.02356066 0.76718134]
 [0.98638341 0.43433763 0.52778388 0.66084496 0.36524299 0.76501063
  0.22826207 0.24399456 0.29680796 0.84984019]
 [0.31025119 0.42753743 0.41258312 0.0780498  0.37541978 0.31121193
  0.14996745 0.54861977 0.57003888 0.76026194]
 [0.23908284 0.55819552 0.16919877 0.30914001 0.8237819  0.98568706
  0.75745013 0.67153763 0.02727932 0.58411624]
 [0.56981302 0.38769264 0.60615205 0.30689957 0.82463564 0.27636908
  0.91862765 0.6130122  0.62889283 0.26553796]
 [0.88123601 0.72740867 0.45915811 0.94134327 0.12646442 0.84136243
  0.40328543 0.02562018 0.93586783 0.16707705]
 [0.22392641 0.84335515 0.7408088  0.39104173 0.17448676 0.31804754
  0.07853868 0.81541457 0.74865042 0.00199907]
 [0.04472458 0.14711397 0.74998149 0.60828489 0.50295302 0.1845215
  0.82943533 0.095855   0.47824788 0.86732979]
 [0.56138345 0.37498386 0.4737983  0.27328406 0.47498926 0.94975613
  0.7613

14.创建一个长度为30的随机矩阵，并找到平均值

In [67]:
z = np.random.random(30)
print(z,z.mean())

[0.24089413 0.54523477 0.12737431 0.07478073 0.83061045 0.72315534
 0.0839117  0.55758215 0.52510555 0.50731173 0.03240473 0.96037058
 0.92764989 0.96441457 0.53338207 0.12663989 0.7322891  0.94973282
 0.25926606 0.2837686  0.44705647 0.15861842 0.56858139 0.44953271
 0.8874232  0.21483149 0.16794997 0.49563388 0.51662551 0.4061961 ] 0.4766109432341416


15.创建一个二维矩阵，边界为1，其余为0

In [70]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16.对于一个存在的数组，如何填充其边界为0

In [75]:
z = np.ones((5,5))
z = np.pad(z,pad_width = 1, mode = 'constant', constant_values = 0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17.以下表达式运行的结果分别是什么

In [78]:
# 0 * np.nan
print(0 * np.nan)
#np.nan == np.nan
print(np.nan == np.nan)
#np.inf > np.nan
print(np.inf > np.nan)
#np.nan - np.nan
print(np.nan - np.nan)
#0.3 == 3*0.1
print( 0.3 == 3*0.1)

nan
False
False
nan
False


18.创建一个5*5的矩阵，并设置值1，2，3，4落在其对角线下方位置

In [79]:
z = np.diag(1+np.arange(4),k = -1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19.创建一个8*8的矩阵，并且设置成棋盘样式

In [87]:
z = np.zeros((8,8),dtype = int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20.考虑一个（6，7，8）形状的数组，其第100个元素的索引（x,y,z)是什么？

In [92]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21.用tile函数去创建一个8*8的棋盘样式矩阵

In [96]:
print(np.tile([[0,1],[1,0]],(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22.对一个随机矩阵进行归一化处理

In [98]:
z = np.random.random((5,5))
zmin, zmax = z.min(),z.max()
z = (z - zmin) / zmax - zmin
print(z)

[[ 0.55861531  0.24976761  0.02736384  0.12797717  0.04507099]
 [ 0.04028097  0.09401461 -0.04801606  0.43605431  0.75187792]
 [ 0.22254504  0.83448987  0.58722864  0.74089374  0.84773991]
 [ 0.62510081  0.68076644 -0.0722285   0.05175624  0.18730864]
 [ 0.20929986  0.35085155 -0.04926144  0.21993637 -0.07315795]]


23.创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype?

In [99]:
color = np.dtype([('r',np.ubyte,1),
                 ('g',np.ubyte,1),
                 ('b',np.ubyte,1),
                 ('a',np.ubyte,1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


24.一个5 * 3的矩阵与一个3 * 2的矩阵相乘，实矩阵乘积是什么？

In [101]:
a = np.random.random((5,3))
b = np.random.random((3,2))
print(np.dot(a,b))

[[1.3445716  2.01845668]
 [0.88848703 1.27331385]
 [0.61297254 1.17792049]
 [1.23843121 2.03627704]
 [1.2377514  1.81647428]]


25.给定一个一维数组，对其在3到8之间的所有元素取反

In [102]:
z = np.arange(11)
z[(z>=3)&(z<=8)] *= -1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


26.下面脚本运行后的结果是什么

In [106]:
print(sum(range(5),-1))
print(np.sum(range(5),-1))

10
10


27.考虑一个整数向量z,下列表达合法的是哪个？

In [108]:
#z**z
#2<<z>>2
#z<-z
#lj*z
#z/1/1
#z<z>z
z = np.arange(5)

28.下列表达式的结果分别是什么？

In [112]:
#np.array(0) / np.array(0)
#np.array(0) // np.array(0)
#np.array([np.nan]).astype(int).astype(float)

29.如何从零位对浮点数组做舍入？

In [114]:
z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[-10.  -7.   3.   1.  -5.  -3.  -6.  10.   8.   5.]


30.如何找到两个数组中的共同元素？

In [116]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[5 6 7 9]


31.如何忽略所有numpy警告

In [123]:
import warnings
warnings.filterwarnings('ignore')
z = np.ones(1) / 0
#defaults = np.seterr(all = 'ignore')
#z = np.ones(1) / 0
#_ = np.seterr(**defaults)
#An equivlent way,with a context manager:
#with np.errstate(divide = 'ignore'):
#    z = np.ones(1) / 0

32.下面的表达式是正确的吗？

In [125]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

33.如何得到昨天，今天，明天的日期？

In [126]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D') 
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print('Yesterday: {}\n Today: {} \n Tomorrow: {} \n'.format(yesterday,today,tomorrow))

Yesterday: 2019-06-20
 Today: 2019-06-21 
 Tomorrow: 2019-06-22 



34.如何得到所有与2016年7月对应的日期？

In [127]:
z = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35.如何直接在位计算(A + B) \* (-A/2)(不建立副本)？

In [130]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out = B )
np.divide(A,2,out = A)
np.negative(A,out = A )
np.multiply(A,B,out = A)

array([-1.5, -1.5, -1.5])

36.用五种不同的方法去提取一个随机数组的整数部分

In [155]:
z = np.random.uniform(0,10,10)
print(z)
print(z.astype(int))
print(z-z%1)
print(ceil(z) - 1)
print(floor(z))
print(trunc(z))

[1.6541471  5.1303339  9.79718527 5.96276924 6.64461929 6.71173987
 1.91118214 2.40884563 5.00911304 4.66946012]
[1 5 9 5 6 6 1 2 5 4]
[1. 5. 9. 5. 6. 6. 1. 2. 5. 4.]
[1. 5. 9. 5. 6. 6. 1. 2. 5. 4.]
[1. 5. 9. 5. 6. 6. 1. 2. 5. 4.]
[1. 5. 9. 5. 6. 6. 1. 2. 5. 4.]


37.创建一个5*5的矩阵，其中每行的数值范围从0到4

In [179]:
z = np.tile(np.arange(5),(5,1))
print(z)
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38.通过考虑一个可生成10个整数的函数，来构建一个数组

In [183]:
def array_func():
    for x in range(10):
        yield  x
z = np.fromiter(array_func(),dtype = float, count = -1 )
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39.创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [184]:
z = np.linspace(0,1,11,endpoint = False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40.创建一个长度为10的随机向量，并将其排序

In [185]:
z = np.random.random(10)
z.sort()
print(z)

[0.10351674 0.12274226 0.19298196 0.27596732 0.32409429 0.45234514
 0.72003367 0.88234888 0.89558492 0.92163295]


41.对于一个小数组，如何用比np.sum更快的方式对其求和？

In [187]:
z = np.arange(10)
print(np.add.reduce(z))

45


42.对于两个随机数组A和B，检查它们是否相等

In [24]:
A = [0,1,4,5]
a = [1,0,4,5]
B = [0,1,4,5]
b = [None,1,4,5]
c = [None,1,4,5]
equal_1 = np.allclose(A,B)
equal_2 = np.allclose(A,a)
print(equal_1)
print(equal_2)
print(np.allclose(c,b))      #只能对数值型数据进行比较

True
False


TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [25]:
equal_1 = np.array_equal(A,B)
equal_2 = np.array_equal(A,a)
print(equal_1)
print(equal_2)
print(np.array_equal(c,b)) #排序影响，各种类型数据都能比较

True
False
True


43. 创建一个只读数组(read-only)

In [40]:
z = np.zeros(10)
z.flags.writeable = False #flags.writeable应该如何查info(),对象只能是数组？

44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [48]:
z = np.random.random((10,2))
X,Y = z[:,0], z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.86042234 0.28162931 1.35583625 0.4071167  0.36663443 0.90289147
 0.25701139 0.99207533 0.15343774 0.43532395]
[0.99193574 0.13896089 0.76225429 0.39689531 1.23228505 1.23824842
 1.16255951 1.41006134 0.48199595 0.4597946 ]


45. 创建一个长度为10的向量，并将向量中最大值替换为1 

In [51]:
z = np.random.random(10)
z[z.argmax()] = 1
print (z)

[0.37597536 0.01302586 0.62857602 0.19368694 0.06023459 0.43159608
 0.60859625 0.85192817 1.         0.096807  ]


In [53]:
z = np.zeros((5,5), [('x',float),('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),
                              np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [54]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


48. 打印每个numpy标量类型的最小值和最大值？

In [62]:
for dtype in [np.int8, np.int32, np.int64]:
    print('{} max: {}'.format(dtype,np.iinfo(dtype).min))
    print('{} min: {}'.format(dtype,np.iinfo(dtype).max))

for dtype in [np.float32, np.float64]:
    print('{} max: {}'.format(dtype,np.finfo(dtype).min))
    print('{} max: {}'.format(dtype,np.finfo(dtype).max))
    print('{} max: {}'.format(dtype,np.finfo(dtype).eps))

<class 'numpy.int8'> max: -128
<class 'numpy.int8'> min: 127
<class 'numpy.int32'> max: -2147483648
<class 'numpy.int32'> min: 2147483647
<class 'numpy.int64'> max: -9223372036854775808
<class 'numpy.int64'> min: 9223372036854775807
<class 'numpy.float32'> max: -3.4028234663852886e+38
<class 'numpy.float32'> max: 3.4028234663852886e+38
<class 'numpy.float32'> max: 1.1920928955078125e-07
<class 'numpy.float64'> max: -1.7976931348623157e+308
<class 'numpy.float64'> max: 1.7976931348623157e+308
<class 'numpy.float64'> max: 2.220446049250313e-16


49. 如何打印一个数组中的所有数值?

In [69]:
np.set_printoptions(threshold = None)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


50. 给定标量时，如何找到数组中最接近标量的值？

In [70]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

78


51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组

In [71]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离

In [72]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.48503    0.49371657 0.34932991 0.32391857 0.55093476
  0.47382556 0.50677712 0.20204055 0.39235799]
 [0.48503    0.         0.02305051 0.13635085 0.74908495 0.1255235
  0.82901856 0.98582413 0.66167473 0.83526169]
 [0.49371657 0.02305051 0.         0.14779102 0.7506351  0.14239261
  0.84697185 0.99182584 0.66643852 0.84928783]
 [0.34932991 0.13635085 0.14779102 0.         0.62546476 0.21564735
  0.70782443 0.85247434 0.53090094 0.70202012]
 [0.32391857 0.74908495 0.7506351  0.62546476 0.         0.84037545
  0.64206037 0.2924695  0.13125839 0.46892264]
 [0.55093476 0.1255235  0.14239261 0.21564735 0.84037545 0.
  0.82927113 1.05769022 0.74161142 0.8650481 ]
 [0.47382556 0.82901856 0.84697185 0.70782443 0.64206037 0.82927113
  0.         0.58339455 0.53017542 0.20009601]
 [0.50677712 0.98582413 0.99182584 0.85247434 0.2924695  1.05769022
  0.58339455 0.         0.3278686  0.38345243]
 [0.20204055 0.66167473 0.66643852 0.53090094 0.13125839 0.74161142
  0.53017542 0.327868

In [73]:
# # 方法2
# # Much faster with scipy
import scipy
# # Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print (D)

[[0.         0.48503    0.49371657 0.34932991 0.32391857 0.55093476
  0.47382556 0.50677712 0.20204055 0.39235799]
 [0.48503    0.         0.02305051 0.13635085 0.74908495 0.1255235
  0.82901856 0.98582413 0.66167473 0.83526169]
 [0.49371657 0.02305051 0.         0.14779102 0.7506351  0.14239261
  0.84697185 0.99182584 0.66643852 0.84928783]
 [0.34932991 0.13635085 0.14779102 0.         0.62546476 0.21564735
  0.70782443 0.85247434 0.53090094 0.70202012]
 [0.32391857 0.74908495 0.7506351  0.62546476 0.         0.84037545
  0.64206037 0.2924695  0.13125839 0.46892264]
 [0.55093476 0.1255235  0.14239261 0.21564735 0.84037545 0.
  0.82927113 1.05769022 0.74161142 0.8650481 ]
 [0.47382556 0.82901856 0.84697185 0.70782443 0.64206037 0.82927113
  0.         0.58339455 0.53017542 0.20009601]
 [0.50677712 0.98582413 0.99182584 0.85247434 0.2924695  1.05769022
  0.58339455 0.         0.3278686  0.38345243]
 [0.20204055 0.66167473 0.66643852 0.53090094 0.13125839 0.74161142
  0.53017542 0.327868

53. 如何将32位的浮点数(float)转换为对应的整数(integer)?

In [93]:
z = np.arange(10,dtype = np.float32).astype(np.int32)
print(z)

[0 1 2 3 4 5 6 7 8 9]


54. 如何读取以下文件? 

In [95]:
from io import StringIO
s = StringIO("1, 2, 3, 4, 5,6,  ,  , 7, 8 ,  , 9,10,11")
data = np.genfromtxt(s,delimiter=",")            
print(data)

[ 1.  2.  3.  4.  5.  6. nan nan  7.  8. nan  9. 10. 11.]


55. 对于numpy数组，enumerate的等价操作是什么？

In [104]:
Z = [1,2,4,5,6,7]
for i,z in enumerate(Z):
    print('Z[{}] : {}'.format(i,z))
    
for i in range(len(Z)):
    print('Z[{}] : {}'.format(i,Z[i]))
    

Z[0] : 1
Z[1] : 2
Z[2] : 4
Z[3] : 5
Z[4] : 6
Z[5] : 7
Z[0] : 1
Z[1] : 2
Z[2] : 4
Z[3] : 5
Z[4] : 6
Z[5] : 7


56. 生成一个通用的二维Gaussian-like数组

In [105]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

57. 对一个二维数组，如何在其内部随机放置p个元素? 

In [106]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


58. 减去一个矩阵中的每一行的平均值 

In [108]:
X = np.random.rand(5, 10)
# # Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

# # 方法2
# # Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
print (Y)

[[-0.44619296  0.51685258  0.31454699  0.38000874 -0.33501972 -0.1262283
  -0.08982451 -0.06143749 -0.25219651  0.09949118]
 [-0.09949004 -0.26284091 -0.4439816   0.37671538  0.37946582  0.3311069
   0.20838143 -0.24642092 -0.17282531 -0.07011076]
 [ 0.09219124 -0.30075527  0.22822879 -0.35504125 -0.0088954   0.39040587
   0.38714041 -0.08495406 -0.29782086 -0.05049948]
 [-0.28132036 -0.18157901  0.22166182 -0.25769794  0.00555861 -0.49030378
   0.14406168  0.15509293  0.17698074  0.50754532]
 [-0.35358391  0.18460148 -0.26711231  0.60605526  0.50696276 -0.04562073
  -0.29558643 -0.09650515 -0.18627205 -0.05293891]]
[[-0.44619296  0.51685258  0.31454699  0.38000874 -0.33501972 -0.1262283
  -0.08982451 -0.06143749 -0.25219651  0.09949118]
 [-0.09949004 -0.26284091 -0.4439816   0.37671538  0.37946582  0.3311069
   0.20838143 -0.24642092 -0.17282531 -0.07011076]
 [ 0.09219124 -0.30075527  0.22822879 -0.35504125 -0.0088954   0.39040587
   0.38714041 -0.08495406 -0.29782086 -0.05049948]
 [-

59. 如何通过第n列对一个数组进行排序? 

In [114]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[3 5 4]
 [2 4 0]
 [4 2 1]]
[[4 2 1]
 [2 4 0]
 [3 5 4]]


60. 如何检查一个二维数组是否有空列？

In [121]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

True


61. 从数组中的给定值中找出最近的值

In [122]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.5485883293847514


62. 如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组? 

In [124]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


63. 创建一个具有name属性的数组类

In [125]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


64. 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)? 

In [126]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 2. 1. 4. 3. 4. 3. 4. 3. 4.]


In [128]:
# # 方法2
np.add.at(Z, I, 1)
print(Z)

[3. 3. 1. 7. 5. 7. 5. 7. 5. 7.]


65. 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)? 

In [129]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66. 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量

In [130]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
# #Note that we should compute 256*256 first. 
# #Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


67. 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？ 

In [131]:
A = np.random.randint(0,10,(3,4,3,4))
# # solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[56 63 48 57]
 [63 31 61 70]
 [72 60 45 47]]


In [132]:
# # 方法2
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (sum)

[[56 63 48 57]
 [63 31 61 70]
 [72 60 45 47]]


68. 考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？

In [133]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.55515568 0.49139189 0.46464727 0.26382553 0.47106378 0.48619057
 0.40513331 0.61455938 0.45220883 0.36395533]


In [134]:
# # 方法2
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.555156
1    0.491392
2    0.464647
3    0.263826
4    0.471064
5    0.486191
6    0.405133
7    0.614559
8    0.452209
9    0.363955
dtype: float64


69. 如何获得点积 dot prodcut的对角线?

In [135]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# # slow version
np.diag(np.dot(A, B))

array([1.22908566, 0.81617563, 1.50562241, 0.95736414, 1.25271243])

In [136]:
## 方法2
# # Fast version
np.sum(A * B.T, axis=1)

array([1.22908566, 0.81617563, 1.50562241, 0.95736414, 1.25271243])

In [137]:
## 方法3
# # Faster version
np.einsum("ij,ji->i", A, B)

array([1.22908566, 0.81617563, 1.50562241, 0.95736414, 1.25271243])

70. 考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？

In [138]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？

In [139]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. 如何对一个数组中任意两行做交换?

In [140]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


73. 考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment

In [141]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 1, 22) ( 1, 84) ( 3, 12) ( 3, 31) ( 6, 22) ( 6, 37) (10, 83) (10, 87)
 (12, 19) (12, 31) (12, 41) (17, 32) (17, 81) (19, 41) (22, 37) (22, 84)
 (24, 37) (24, 49) (28, 30) (28, 85) (30, 85) (32, 81) (33, 55) (33, 75)
 (37, 49) (37, 85) (37, 98) (55, 75) (83, 87) (85, 98)]


74. 给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C

In [142]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


75. 如何通过滑动窗口计算一个数组的平均数?

In [143]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [144]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77. 如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？

In [149]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0])

In [148]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.28919481, -0.75979912, -0.60620469,  0.63644908, -0.78653188,
        0.43856472,  0.75155387,  0.8061824 ,  0.47071546, -0.54780419,
       -0.64078839, -0.98601044, -0.76928906, -0.66710052,  0.35159179,
        0.26879447, -0.60724262,  0.58706513, -0.4762206 ,  0.33033562,
       -0.7422448 , -0.22403076, -0.45172449, -0.21998895,  0.62061237,
        0.5468663 , -0.96534926, -0.22181287, -0.61485778, -0.94000872,
        0.72242042,  0.71202193,  0.81772531, -0.36017163, -0.07046583,
       -0.99787373,  0.66089721,  0.12388201,  0.99056919, -0.63735199,
        0.03418778,  0.02453776, -0.1323882 ,  0.25421048,  0.38681619,
       -0.03348614,  0.6062959 , -0.62249565,  0.28958629,  0.54590315,
        0.77408274, -0.22550518,  0.23581416,  0.77073363, -0.35474383,
       -0.73156642,  0.74306225, -0.58053284,  0.99980723,  0.52807077,
        0.11690838, -0.57320635,  0.12097161,  0.75908258, -0.66376627,
        0.62117038,  0.20528114, -0.70612193, -0.62762162, -0.60

78. 考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？

In [150]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 7.58626998  3.54739053  5.46969192 10.6866648   0.82444955  0.02012875
  9.79817676  3.86612102 15.10953503 12.90053069]


79.考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离？

In [151]:
# # based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.67159581  2.50660772  0.61865304  2.40679494  1.25604152  8.61029948
   1.39275595  8.38044815  8.07256174  2.66418984]
 [10.87168301  4.77903252  5.47576819  3.09306838  1.70469312  3.34859578
   6.56051841  2.58501242 15.66946773  5.43851671]
 [ 5.93954626  3.4481366   1.16194165  1.58103847  0.32452975  7.76895822
   0.86759147  7.57616201  7.77148432  2.83840715]
 [ 8.4679836   8.22644987  3.82993877  6.27920939  5.14847321  0.11817952
   8.79345583  0.53862456 14.95306308  5.19586859]
 [ 6.99339621  7.20294489  1.60272071  4.04721986  3.86476114  2.26218051
   5.67867831  1.80220563 12.11329178  2.14223867]
 [ 5.66870945  1.60757443  2.2121433   4.19551337  2.34872635 10.33524253
   3.80114139 10.247749    5.98598857  4.92883259]
 [ 0.74182589 12.0600016   6.11329284  5.98038687  8.19743754  0.06565166
   3.95211396  0.21027756  5.03778495  4.411274  ]
 [ 1.37068494  7.87604578  5.11460952  1.64057128  3.92180558  4.4220092
   0.34042599  4.52108668  4.78467913  5.26627583]
 

80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [154]:
import warnings
warnings.filterwarnings('ignore')
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[8 4 7 3 9 7 8 1 1 5]
 [0 0 7 6 4 5 4 7 3 9]
 [1 9 9 6 8 4 2 6 7 3]
 [1 9 9 6 2 9 2 4 2 8]
 [5 0 4 1 4 1 8 1 8 7]
 [1 0 8 3 7 2 2 4 2 8]
 [3 5 4 8 7 7 6 8 5 9]
 [6 6 1 4 2 6 2 9 2 5]
 [3 9 3 7 3 9 2 9 4 3]
 [9 2 6 4 5 1 1 3 2 5]]
[[0 0 0 0 0]
 [0 8 4 7 3]
 [0 0 0 7 6]
 [0 1 9 9 6]
 [0 1 9 9 6]]


81. 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]? 

In [156]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. 计算一个矩阵的秩

In [157]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


83. 如何找到一个数组中出现频率最高的值？

In [160]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

7


84. 从一个10x10的矩阵中提取出连续的3x3区块

In [161]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[0 1 1]
   [0 1 0]
   [1 4 4]]

  [[1 1 4]
   [1 0 3]
   [4 4 0]]

  [[1 4 1]
   [0 3 0]
   [4 0 0]]

  [[4 1 2]
   [3 0 2]
   [0 0 1]]

  [[1 2 0]
   [0 2 3]
   [0 1 2]]

  [[2 0 4]
   [2 3 4]
   [1 2 4]]

  [[0 4 0]
   [3 4 2]
   [2 4 3]]

  [[4 0 1]
   [4 2 4]
   [4 3 0]]]


 [[[0 1 0]
   [1 4 4]
   [2 3 1]]

  [[1 0 3]
   [4 4 0]
   [3 1 2]]

  [[0 3 0]
   [4 0 0]
   [1 2 0]]

  [[3 0 2]
   [0 0 1]
   [2 0 3]]

  [[0 2 3]
   [0 1 2]
   [0 3 2]]

  [[2 3 4]
   [1 2 4]
   [3 2 3]]

  [[3 4 2]
   [2 4 3]
   [2 3 4]]

  [[4 2 4]
   [4 3 0]
   [3 4 0]]]


 [[[1 4 4]
   [2 3 1]
   [0 1 1]]

  [[4 4 0]
   [3 1 2]
   [1 1 0]]

  [[4 0 0]
   [1 2 0]
   [1 0 2]]

  [[0 0 1]
   [2 0 3]
   [0 2 1]]

  [[0 1 2]
   [0 3 2]
   [2 1 1]]

  [[1 2 4]
   [3 2 3]
   [1 1 0]]

  [[2 4 3]
   [2 3 4]
   [1 0 3]]

  [[4 3 0]
   [3 4 0]
   [0 3 4]]]


 [[[2 3 1]
   [0 1 1]
   [0 1 0]]

  [[3 1 2]
   [1 1 0]
   [1 0 0]]

  [[1 2 0]
   [1 0 2]
   [0 0 4]]

  [[2 0 3]
   [0 2 1]
   [0 4 0]]

  [[0 3 2]
   

85. 创建一个满足 Z[i,j] == Z[j,i]的子类 

In [162]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 6 11 14 11 17]
 [11  5  5  3  1]
 [14  5  1 42  9]
 [11  3 42  1  2]
 [17  1  9  2  5]]


86. 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？

In [163]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)
# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


87. 对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)? 

In [164]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88. 如何利用numpy数组实现Game of Life?

In [165]:
def iterate(Z):
#     # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

#     # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


89. 如何找到一个数组的第n个最大值? 

In [166]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# # Slow
print (Z[np.argsort(Z)[-n:]])

# # 方法2
# # Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)

In [167]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


91. 如何从一个正常数组创建记录数组(record array)? 

In [168]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


92. 考虑一个大向量Z, 用三种不同的方法计算它的立方

In [176]:
x = np.random.rand()
print(np.power(x,3))

## 方法2
print(x*x*x)

## 方法3
print(x**3)

0.9269187925433168
0.9269187925433169
0.9269187925433168


93. 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？ 

In [177]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[0 4 5 6]


94. 考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3])

In [178]:
Z = np.random.randint(0,5,(10,3))
print (Z)

# # solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[2 1 4]
 [1 2 0]
 [3 0 1]
 [3 4 0]
 [1 2 4]
 [1 0 0]
 [0 2 4]
 [4 4 3]
 [0 0 4]
 [1 2 3]]
[[2 1 4]
 [1 2 0]
 [3 0 1]
 [3 4 0]
 [1 2 4]
 [1 0 0]
 [0 2 4]
 [4 4 3]
 [0 0 4]
 [1 2 3]]


In [179]:
# # 方法2
# # soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print (U)

[[2 1 4]
 [1 2 0]
 [3 0 1]
 [3 4 0]
 [1 2 4]
 [1 0 0]
 [0 2 4]
 [4 4 3]
 [0 0 4]
 [1 2 3]]


95. 将一个整数向量转换为matrix binary的表现形式

In [181]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. 给定一个二维数组，如何提取出唯一的(unique)行?

In [182]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


97. 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数

In [183]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)

sum
5.934133380103298


In [184]:
print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B

A * B
[0.05445689 0.41020686 0.48288934 0.11270607 0.03740868 0.03707755
 0.73577061 0.00710045 0.13766691 0.49822331]


In [185]:
print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)

inner
2.513506667374801


In [186]:
print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

outer
[[0.05445689 0.12453605 0.18183699 0.12823713 0.01927265 0.01606259
  0.24111126 0.003709   0.27038382 0.18965371]
 [0.17937447 0.41020686 0.59894929 0.42239776 0.0634818  0.05290825
  0.79419164 0.012217   0.89061196 0.62469662]
 [0.14461662 0.33072002 0.48288934 0.34054866 0.05118077 0.04265608
  0.64029908 0.00984968 0.71803579 0.50364755]
 [0.0478615  0.10945324 0.15981434 0.11270607 0.0169385  0.01411722
  0.21190978 0.0032598  0.23763708 0.16668436]
 [0.10570215 0.24172753 0.35295004 0.2489114  0.03740868 0.03117788
  0.46800285 0.00719926 0.52482161 0.36812248]
 [0.12570377 0.28746871 0.41973744 0.29601196 0.04448739 0.03707755
  0.55656126 0.00856155 0.62413162 0.43778091]
 [0.16617962 0.38003189 0.55489035 0.39132602 0.05881206 0.0490163
  0.73577061 0.01131831 0.82509821 0.5787437 ]
 [0.10425142 0.23840989 0.34810591 0.24549516 0.03689526 0.03074997
  0.46157965 0.00710045 0.51761859 0.36307011]
 [0.02772692 0.06340798 0.09258296 0.0652924  0.00981274 0.00817833
  0.122

98. 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)?

In [187]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [188]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


100. 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。

In [189]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.0934237   0.27817968]
